// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"chat-app-svr/rpc/user/internal/logic"
	"chat-app-svr/rpc/user/internal/svc"
	"chat-app-svr/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Ping(ctx context.Context, in *user.Request) (*user.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserServer) UserDetail(ctx context.Context, in *user.UserDetailRequest) (*user.UserDetailReply, error) {
	l := logic.NewUserDetailLogic(ctx, s.svcCtx)
	return l.UserDetail(in)
}
