// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0--rc3
// source: feature.proto

package feature

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FeatureServer_ListUserFeatures_FullMethodName    = "/push.FeatureServer/ListUserFeatures"
	FeatureServer_ListArticleFeatures_FullMethodName = "/push.FeatureServer/ListArticleFeatures"
)

// FeatureServerClient is the client API for FeatureServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeatureServerClient interface {
	ListUserFeatures(ctx context.Context, in *UserFeatureRequest, opts ...grpc.CallOption) (FeatureServer_ListUserFeaturesClient, error)
	ListArticleFeatures(ctx context.Context, in *ArticleFeatureRequest, opts ...grpc.CallOption) (FeatureServer_ListArticleFeaturesClient, error)
}

type featureServerClient struct {
	cc grpc.ClientConnInterface
}

func NewFeatureServerClient(cc grpc.ClientConnInterface) FeatureServerClient {
	return &featureServerClient{cc}
}

func (c *featureServerClient) ListUserFeatures(ctx context.Context, in *UserFeatureRequest, opts ...grpc.CallOption) (FeatureServer_ListUserFeaturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &FeatureServer_ServiceDesc.Streams[0], FeatureServer_ListUserFeatures_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &featureServerListUserFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FeatureServer_ListUserFeaturesClient interface {
	Recv() (*UserFeature, error)
	grpc.ClientStream
}

type featureServerListUserFeaturesClient struct {
	grpc.ClientStream
}

func (x *featureServerListUserFeaturesClient) Recv() (*UserFeature, error) {
	m := new(UserFeature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *featureServerClient) ListArticleFeatures(ctx context.Context, in *ArticleFeatureRequest, opts ...grpc.CallOption) (FeatureServer_ListArticleFeaturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &FeatureServer_ServiceDesc.Streams[1], FeatureServer_ListArticleFeatures_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &featureServerListArticleFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FeatureServer_ListArticleFeaturesClient interface {
	Recv() (*ArticleFeature, error)
	grpc.ClientStream
}

type featureServerListArticleFeaturesClient struct {
	grpc.ClientStream
}

func (x *featureServerListArticleFeaturesClient) Recv() (*ArticleFeature, error) {
	m := new(ArticleFeature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FeatureServerServer is the server API for FeatureServer service.
// All implementations must embed UnimplementedFeatureServerServer
// for forward compatibility
type FeatureServerServer interface {
	ListUserFeatures(*UserFeatureRequest, FeatureServer_ListUserFeaturesServer) error
	ListArticleFeatures(*ArticleFeatureRequest, FeatureServer_ListArticleFeaturesServer) error
	mustEmbedUnimplementedFeatureServerServer()
}

// UnimplementedFeatureServerServer must be embedded to have forward compatible implementations.
type UnimplementedFeatureServerServer struct {
}

func (UnimplementedFeatureServerServer) ListUserFeatures(*UserFeatureRequest, FeatureServer_ListUserFeaturesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListUserFeatures not implemented")
}
func (UnimplementedFeatureServerServer) ListArticleFeatures(*ArticleFeatureRequest, FeatureServer_ListArticleFeaturesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListArticleFeatures not implemented")
}
func (UnimplementedFeatureServerServer) mustEmbedUnimplementedFeatureServerServer() {}

// UnsafeFeatureServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeatureServerServer will
// result in compilation errors.
type UnsafeFeatureServerServer interface {
	mustEmbedUnimplementedFeatureServerServer()
}

func RegisterFeatureServerServer(s grpc.ServiceRegistrar, srv FeatureServerServer) {
	s.RegisterService(&FeatureServer_ServiceDesc, srv)
}

func _FeatureServer_ListUserFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserFeatureRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeatureServerServer).ListUserFeatures(m, &featureServerListUserFeaturesServer{stream})
}

type FeatureServer_ListUserFeaturesServer interface {
	Send(*UserFeature) error
	grpc.ServerStream
}

type featureServerListUserFeaturesServer struct {
	grpc.ServerStream
}

func (x *featureServerListUserFeaturesServer) Send(m *UserFeature) error {
	return x.ServerStream.SendMsg(m)
}

func _FeatureServer_ListArticleFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ArticleFeatureRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeatureServerServer).ListArticleFeatures(m, &featureServerListArticleFeaturesServer{stream})
}

type FeatureServer_ListArticleFeaturesServer interface {
	Send(*ArticleFeature) error
	grpc.ServerStream
}

type featureServerListArticleFeaturesServer struct {
	grpc.ServerStream
}

func (x *featureServerListArticleFeaturesServer) Send(m *ArticleFeature) error {
	return x.ServerStream.SendMsg(m)
}

// FeatureServer_ServiceDesc is the grpc.ServiceDesc for FeatureServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeatureServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "push.FeatureServer",
	HandlerType: (*FeatureServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUserFeatures",
			Handler:       _FeatureServer_ListUserFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListArticleFeatures",
			Handler:       _FeatureServer_ListArticleFeatures_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "feature.proto",
}
