// Code generated by goctl. DO NOT EDIT.
// Source: send_svr.proto

package server

import (
	"context"

	"chat-app-svr/rpc/send_svr/internal/logic"
	"chat-app-svr/rpc/send_svr/internal/svc"
	"chat-app-svr/rpc/send_svr/send"
)

type SenderServer struct {
	svcCtx *svc.ServiceContext
	send.UnimplementedSenderServer
}

func NewSenderServer(svcCtx *svc.ServiceContext) *SenderServer {
	return &SenderServer{
		svcCtx: svcCtx,
	}
}

func (s *SenderServer) SendMessage(ctx context.Context, in *send.SendMessageRequest) (*send.SendMessageReply, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *SenderServer) SendGroupMessage(ctx context.Context, in *send.SendGroupMessageRequest) (*send.SendGroupMessageReply, error) {
	l := logic.NewSendGroupMessageLogic(ctx, s.svcCtx)
	return l.SendGroupMessage(in)
}
