// Code generated by goctl. DO NOT EDIT.
// Source: push_svr.proto

package server

import (
	"context"

	"chat-app-svr/rpc/push_svr/internal/logic"
	"chat-app-svr/rpc/push_svr/internal/svc"
	"chat-app-svr/rpc/push_svr/push"
)

type PusherServer struct {
	svcCtx *svc.ServiceContext
	push.UnimplementedPusherServer
}

func NewPusherServer(svcCtx *svc.ServiceContext) *PusherServer {
	return &PusherServer{
		svcCtx: svcCtx,
	}
}

func (s *PusherServer) PushMessage(ctx context.Context, in *push.PushMessageRequest) (*push.PushMessageReply, error) {
	l := logic.NewPushMessageLogic(ctx, s.svcCtx)
	return l.PushMessage(in)
}
