apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: airec-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airec-server
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50