// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package server

import (
	"context"

	"chat-app-svr/rpc/chat/chat"
	"chat-app-svr/rpc/chat/internal/logic"
	"chat-app-svr/rpc/chat/internal/svc"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	chat.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServer) PushMessage(ctx context.Context, in *chat.PushMessageRequest) (*chat.PushMessageReply, error) {
	l := logic.NewPushMessageLogic(ctx, s.svcCtx)
	return l.PushMessage(in)
}
