// Code generated by goctl. DO NOT EDIT.
package types

type GetUserReq struct {
	UserId int64 `form:"userId"`
}

type GetUserResp struct {
	UserId      int64  `json:"userId"`
	PhoneNumber string `json:"phoneNumber"`
}

type LoginReq struct {
	PhoneNumber string `form:"phoneNumber"`
	Password    string `form:"password"`
}

type LoginResp struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}
