// Code generated by goctl. DO NOT EDIT.
// Source: notification.proto

package server

import (
	"context"

	"chat-app-svr/rpc/notification/internal/logic"
	"chat-app-svr/rpc/notification/internal/svc"
	"chat-app-svr/rpc/notification/notification"
)

type NotificationServer struct {
	svcCtx *svc.ServiceContext
	notification.UnimplementedNotificationServer
}

func NewNotificationServer(svcCtx *svc.ServiceContext) *NotificationServer {
	return &NotificationServer{
		svcCtx: svcCtx,
	}
}

func (s *NotificationServer) PushMessage(ctx context.Context, in *notification.PushMessageRequest) (*notification.PushMessageReply, error) {
	l := logic.NewPushMessageLogic(ctx, s.svcCtx)
	return l.PushMessage(in)
}
