// Code generated by goctl. DO NOT EDIT.
// Source: feature.proto

package server

import (
	"feature_server/feature"
	"feature_server/internal/logic"
	"feature_server/internal/svc"
)

type FeatureServerServer struct {
	svcCtx *svc.ServiceContext
	feature.UnimplementedFeatureServerServer
}

func NewFeatureServerServer(svcCtx *svc.ServiceContext) *FeatureServerServer {
	return &FeatureServerServer{
		svcCtx: svcCtx,
	}
}

func (s *FeatureServerServer) ListUserFeatures(in *feature.UserFeatureRequest, stream feature.FeatureServer_ListUserFeaturesServer) error {
	l := logic.NewListUserFeaturesLogic(stream.Context(), s.svcCtx)
	return l.ListUserFeatures(in, stream)
}

func (s *FeatureServerServer) ListArticleFeatures(in *feature.ArticleFeatureRequest, stream feature.FeatureServer_ListArticleFeaturesServer) error {
	l := logic.NewListArticleFeaturesLogic(stream.Context(), s.svcCtx)
	return l.ListArticleFeatures(in, stream)
}
