// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// createTodoCreateTodo includes the requested fields of the GraphQL type Todo.
type createTodoCreateTodo struct {
	User createTodoCreateTodoUser `json:"user"`
	Text string                   `json:"text"`
	Done bool                     `json:"done"`
}

// GetUser returns createTodoCreateTodo.User, and is useful for accessing the field via an interface.
func (v *createTodoCreateTodo) GetUser() createTodoCreateTodoUser { return v.User }

// GetText returns createTodoCreateTodo.Text, and is useful for accessing the field via an interface.
func (v *createTodoCreateTodo) GetText() string { return v.Text }

// GetDone returns createTodoCreateTodo.Done, and is useful for accessing the field via an interface.
func (v *createTodoCreateTodo) GetDone() bool { return v.Done }

// createTodoCreateTodoUser includes the requested fields of the GraphQL type User.
type createTodoCreateTodoUser struct {
	Id string `json:"id"`
}

// GetId returns createTodoCreateTodoUser.Id, and is useful for accessing the field via an interface.
func (v *createTodoCreateTodoUser) GetId() string { return v.Id }

// createTodoResponse is returned by createTodo on success.
type createTodoResponse struct {
	CreateTodo createTodoCreateTodo `json:"createTodo"`
}

// GetCreateTodo returns createTodoResponse.CreateTodo, and is useful for accessing the field via an interface.
func (v *createTodoResponse) GetCreateTodo() createTodoCreateTodo { return v.CreateTodo }

// findTodosResponse is returned by findTodos on success.
type findTodosResponse struct {
	Todos []findTodosTodosTodo `json:"todos"`
}

// GetTodos returns findTodosResponse.Todos, and is useful for accessing the field via an interface.
func (v *findTodosResponse) GetTodos() []findTodosTodosTodo { return v.Todos }

// findTodosTodosTodo includes the requested fields of the GraphQL type Todo.
type findTodosTodosTodo struct {
	User findTodosTodosTodoUser `json:"user"`
}

// GetUser returns findTodosTodosTodo.User, and is useful for accessing the field via an interface.
func (v *findTodosTodosTodo) GetUser() findTodosTodosTodoUser { return v.User }

// findTodosTodosTodoUser includes the requested fields of the GraphQL type User.
type findTodosTodosTodoUser struct {
	Name string `json:"name"`
}

// GetName returns findTodosTodosTodoUser.Name, and is useful for accessing the field via an interface.
func (v *findTodosTodosTodoUser) GetName() string { return v.Name }

// The query or mutation executed by createTodo.
const createTodo_Operation = `
mutation createTodo {
	createTodo(input: {text:"todo",userId:"1"}) {
		user {
			id
		}
		text
		done
	}
}
`

func createTodo(
	ctx_ context.Context,
	client_ graphql.Client,
) (*createTodoResponse, error) {
	req_ := &graphql.Request{
		OpName: "createTodo",
		Query:  createTodo_Operation,
	}
	var err_ error

	var data_ createTodoResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by findTodos.
const findTodos_Operation = `
query findTodos {
	todos {
		user {
			name
		}
	}
}
`

func findTodos(
	ctx_ context.Context,
	client_ graphql.Client,
) (*findTodosResponse, error) {
	req_ := &graphql.Request{
		OpName: "findTodos",
		Query:  findTodos_Operation,
	}
	var err_ error

	var data_ findTodosResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
